### ISSUE TITLE
Module 4.1

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-ossonts#10]
👋 Hi, you are missing the Module 4.1 Assignment. Please post it here in this thread.

**Comment by ossonts** [comment]
https://education.github.community/t/module-4-exercise-1-student-programs/26002/573
ossonts
Steven Ossont
Jun 18
Describe the existing technical student communities on your campus. Who is served? Where are there gaps?
Software Engineering students are the main focus. They select and join groups for a yearlong project. There is a need to raise the skills that each student brings to these group projects.

Choose one GitHub Education program. How could it support your on-campus student communities?
Students need real-time feedback and this can be in the form of actions/unit tests. For this to work well the inbuilt grading option looks good as well as git templates. Where the exercise is the key focus, anything that deals with env/admin is good, for example, repl.it is a serious consideration.

What would you need to do in order to support the growth of student tech communities on campus?
For communities or group (coursework/assessment) to get rapid feedback the ability to run tests from a secondary repository (hidden) using a git runner (self-hosted) would be useful – currently each repository needs to enable workflow and there is a need for one runner per repository (Unlike Gitlab).

Also the ability to update the source repository (to amend any assignment errors) and push to students would be handy. Along with the ability to have a single runner to ‘test’ all student contributions. This would provide flexibility for powerful feedback.
